// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5xJcYKYdvOuNLAxHHFq6HN5LpRA-vDk',
    appId: '1:721631261035:web:cbf84b0a0b119bfe5a5c2e',
    messagingSenderId: '721631261035',
    projectId: 'uniparty-9b14f',
    authDomain: 'uniparty-9b14f.firebaseapp.com',
    storageBucket: 'uniparty-9b14f.appspot.com',
    measurementId: 'G-W2X413JM9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQ3-rMGcXRtYIIhmtq77GTpwCVFP4g1Q',
    appId: '1:721631261035:android:4f7f52c65b89b19b5a5c2e',
    messagingSenderId: '721631261035',
    projectId: 'uniparty-9b14f',
    storageBucket: 'uniparty-9b14f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzepjSVy85ArYvoZ-5Tnp3_co0JYS1yj0',
    appId: '1:721631261035:ios:b03a057acf6b74a25a5c2e',
    messagingSenderId: '721631261035',
    projectId: 'uniparty-9b14f',
    storageBucket: 'uniparty-9b14f.appspot.com',
    iosClientId: '721631261035-pdlj39q119ujh7ls88hkmvkvc243mjo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.throwAParty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzepjSVy85ArYvoZ-5Tnp3_co0JYS1yj0',
    appId: '1:721631261035:ios:b03a057acf6b74a25a5c2e',
    messagingSenderId: '721631261035',
    projectId: 'uniparty-9b14f',
    storageBucket: 'uniparty-9b14f.appspot.com',
    iosClientId: '721631261035-pdlj39q119ujh7ls88hkmvkvc243mjo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.throwAParty',
  );
}
